services:
  web:
    build: ./djangobnb_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend/ # insist to usr
    ports:
      - 8000:8000 # dockerport:localport
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=djangobnbdb

volumes:
  postgres_data:

